/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Feedback = {
  _id: string;
  _type: "feedback";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  user: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "user";
  };
  content: string;
  createdAt: string;
  archived?: boolean;
};

export type Booking = {
  _id: string;
  _type: "booking";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  host: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "user";
  };
  meetingType?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "meetingType";
  };
  guestName: string;
  guestEmail: string;
  startTime: string;
  endTime: string;
  googleEventId?: string;
  meetLink?: string;
  notes?: string;
};

export type MeetingType = {
  _id: string;
  _type: "meetingType";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  duration: 15 | 30 | 45 | 60 | 90;
  description?: string;
  host: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "user";
  };
  isDefault?: boolean;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type ConnectedAccount = {
  _type: "connectedAccount";
  accountId: string;
  email: string;
  provider?: "google";
  accessToken?: string;
  refreshToken?: string;
  expiryDate?: number;
  isDefault?: boolean;
  connectedAt?: string;
};

export type AvailabilitySlot = {
  _type: "availabilitySlot";
  startDateTime: string;
  endDateTime: string;
};

export type User = {
  _id: string;
  _type: "user";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  clerkId: string;
  name?: string;
  email?: string;
  slug?: Slug;
  availability?: Array<{
    _key: string;
  } & AvailabilitySlot>;
  connectedAccounts?: Array<{
    _key: string;
  } & ConnectedAccount>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = Feedback | Booking | MeetingType | Slug | ConnectedAccount | AvailabilitySlot | User | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityImageHotspot | SanityImageCrop | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: sanity/queries/users.ts
// Variable: USER_BY_CLERK_ID_QUERY
// Query: *[  _type == "user"  && clerkId == $clerkId][0]{  _id,  _type,  clerkId,  name,  email,  slug,  availability[]{    _key,    startDateTime,    endDateTime  },  connectedAccounts[]{    _key,    accountId,    email,    provider,    isDefault,    connectedAt  }}
export type USER_BY_CLERK_ID_QUERYResult = {
  _id: string;
  _type: "user";
  clerkId: string;
  name: string | null;
  email: string | null;
  slug: Slug | null;
  availability: Array<{
    _key: string;
    startDateTime: string;
    endDateTime: string;
  }> | null;
  connectedAccounts: Array<{
    _key: string;
    accountId: string;
    email: string;
    provider: "google" | null;
    isDefault: boolean | null;
    connectedAt: string | null;
  }> | null;
} | null;
// Variable: USER_BY_SLUG_QUERY
// Query: *[  _type == "user"  && slug.current == $slug][0]{  _id,  _type,  name,  email,  slug,  availability[]{    _key,    startDateTime,    endDateTime  }}
export type USER_BY_SLUG_QUERYResult = {
  _id: string;
  _type: "user";
  name: string | null;
  email: string | null;
  slug: Slug | null;
  availability: Array<{
    _key: string;
    startDateTime: string;
    endDateTime: string;
  }> | null;
} | null;
// Variable: USER_WITH_TOKENS_QUERY
// Query: *[  _type == "user"  && clerkId == $clerkId][0]{  _id,  connectedAccounts[]{    _key,    accountId,    email,    accessToken,    refreshToken,    expiryDate,    isDefault  }}
export type USER_WITH_TOKENS_QUERYResult = {
  _id: string;
  connectedAccounts: Array<{
    _key: string;
    accountId: string;
    email: string;
    accessToken: string | null;
    refreshToken: string | null;
    expiryDate: number | null;
    isDefault: boolean | null;
  }> | null;
} | null;
// Variable: USER_ID_BY_ACCOUNT_KEY_QUERY
// Query: *[  _type == "user"  && defined(connectedAccounts[_key == $accountKey])][0]{  _id}
export type USER_ID_BY_ACCOUNT_KEY_QUERYResult = {
  _id: string;
} | null;
// Variable: USER_ID_BY_CLERK_ID_QUERY
// Query: *[  _type == "user"  && clerkId == $clerkId][0]{  _id}
export type USER_ID_BY_CLERK_ID_QUERYResult = {
  _id: string;
} | null;
// Variable: USER_WITH_AVAILABILITY_QUERY
// Query: *[  _type == "user"  && clerkId == $clerkId][0]{  _id,  availability[]{    _key,    startDateTime,    endDateTime  }}
export type USER_WITH_AVAILABILITY_QUERYResult = {
  _id: string;
  availability: Array<{
    _key: string;
    startDateTime: string;
    endDateTime: string;
  }> | null;
} | null;
// Variable: USER_WITH_CONNECTED_ACCOUNTS_QUERY
// Query: *[  _type == "user"  && clerkId == $clerkId][0]{  _id,  connectedAccounts[]{    accountId  }}
export type USER_WITH_CONNECTED_ACCOUNTS_QUERYResult = {
  _id: string;
  connectedAccounts: Array<{
    accountId: string;
  }> | null;
} | null;
// Variable: HOST_BY_SLUG_WITH_TOKENS_QUERY
// Query: *[  _type == "user"  && slug.current == $slug][0]{  _id,  name,  email,  slug,  availability[]{    _key,    startDateTime,    endDateTime  },  connectedAccounts[]{    _key,    accountId,    email,    accessToken,    refreshToken,    expiryDate,    isDefault  }}
export type HOST_BY_SLUG_WITH_TOKENS_QUERYResult = {
  _id: string;
  name: string | null;
  email: string | null;
  slug: Slug | null;
  availability: Array<{
    _key: string;
    startDateTime: string;
    endDateTime: string;
  }> | null;
  connectedAccounts: Array<{
    _key: string;
    accountId: string;
    email: string;
    accessToken: string | null;
    refreshToken: string | null;
    expiryDate: number | null;
    isDefault: boolean | null;
  }> | null;
} | null;
// Variable: USER_CONNECTED_ACCOUNTS_DISPLAY_QUERY
// Query: *[  _type == "user"  && clerkId == $clerkId][0]{  connectedAccounts[]{    _key,    accountId,    email,    isDefault  }}
export type USER_CONNECTED_ACCOUNTS_DISPLAY_QUERYResult = {
  connectedAccounts: Array<{
    _key: string;
    accountId: string;
    email: string;
    isDefault: boolean | null;
  }> | null;
} | null;
// Variable: USER_SLUG_QUERY
// Query: *[  _type == "user"  && clerkId == $clerkId][0]{  _id,  name,  slug}
export type USER_SLUG_QUERYResult = {
  _id: string;
  name: string | null;
  slug: Slug | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "*[\n  _type == \"user\"\n  && clerkId == $clerkId\n][0]{\n  _id,\n  _type,\n  clerkId,\n  name,\n  email,\n  slug,\n  availability[]{\n    _key,\n    startDateTime,\n    endDateTime\n  },\n  connectedAccounts[]{\n    _key,\n    accountId,\n    email,\n    provider,\n    isDefault,\n    connectedAt\n  }\n}": USER_BY_CLERK_ID_QUERYResult;
    "*[\n  _type == \"user\"\n  && slug.current == $slug\n][0]{\n  _id,\n  _type,\n  name,\n  email,\n  slug,\n  availability[]{\n    _key,\n    startDateTime,\n    endDateTime\n  }\n}": USER_BY_SLUG_QUERYResult;
    "*[\n  _type == \"user\"\n  && clerkId == $clerkId\n][0]{\n  _id,\n  connectedAccounts[]{\n    _key,\n    accountId,\n    email,\n    accessToken,\n    refreshToken,\n    expiryDate,\n    isDefault\n  }\n}": USER_WITH_TOKENS_QUERYResult;
    "*[\n  _type == \"user\"\n  && defined(connectedAccounts[_key == $accountKey])\n][0]{\n  _id\n}": USER_ID_BY_ACCOUNT_KEY_QUERYResult;
    "*[\n  _type == \"user\"\n  && clerkId == $clerkId\n][0]{\n  _id\n}": USER_ID_BY_CLERK_ID_QUERYResult;
    "*[\n  _type == \"user\"\n  && clerkId == $clerkId\n][0]{\n  _id,\n  availability[]{\n    _key,\n    startDateTime,\n    endDateTime\n  }\n}": USER_WITH_AVAILABILITY_QUERYResult;
    "*[\n  _type == \"user\"\n  && clerkId == $clerkId\n][0]{\n  _id,\n  connectedAccounts[]{\n    accountId\n  }\n}": USER_WITH_CONNECTED_ACCOUNTS_QUERYResult;
    "*[\n  _type == \"user\"\n  && slug.current == $slug\n][0]{\n  _id,\n  name,\n  email,\n  slug,\n  availability[]{\n    _key,\n    startDateTime,\n    endDateTime\n  },\n  connectedAccounts[]{\n    _key,\n    accountId,\n    email,\n    accessToken,\n    refreshToken,\n    expiryDate,\n    isDefault\n  }\n}": HOST_BY_SLUG_WITH_TOKENS_QUERYResult;
    "*[\n  _type == \"user\"\n  && clerkId == $clerkId\n][0]{\n  connectedAccounts[]{\n    _key,\n    accountId,\n    email,\n    isDefault\n  }\n}": USER_CONNECTED_ACCOUNTS_DISPLAY_QUERYResult;
    "*[\n  _type == \"user\"\n  && clerkId == $clerkId\n][0]{\n  _id,\n  name,\n  slug\n}": USER_SLUG_QUERYResult;
  }
}
